### ISSUE TITLE
关于tcam和sram表的疑问

### ISSUE THREAD

**Issue by git-liusen** [InspiringGroup-Lab/Brain-on-Switch#2]
作者，您好，除了argmax用的TCAM，模型中01比特的映射使用的表格，是SRAM实现的，p4代码声明表格时@ways(1)就是表示使用sram实现表格吗，不声明的话就是tcam表吗。

**Comment by yanjz22** [comment]
> 作者，您好，除了argmax用的TCAM，模型中01比特的映射使用的表格，是SRAM实现的，p4代码声明表格时@ways(1)就是表示使用sram实现表格吗，不声明的话就是tcam表吗。

No, it is not the case. The annotation @ways(n) declares the ways of an exact-match table, without explicitly indicating that this table will be placed in TCAM or SRAM. An annotatation @ternary(0/1) specifies if the match-action table should be placed within SRAM/TCAM respectively. All these annotations are not all necessary. When there is no annotation, the compiler will decide how to implement the tables.

**Comment by git-liusen** [comment]
thanks for your response!
