### ISSUE TITLE
有详细的readme文档吗？

### ISSUE THREAD

**Issue by Akwardxq** [InspiringGroup-Lab/Brain-on-Switch#3]
您好，我想复现这个实验。我这边有一台可编程交换机，但是我不知道该怎么操作，具体来说就是整个实验的过程指导...请问有详细点的readme文档吗？

**Comment by ruin1732** [comment]
> 您好，我想复现这个实验。我这边有一台可编程交换机，但是我不知道该怎么操作，具体来说就是整个实验的过程指导...请问有详细点的readme文档吗？
您好，请问您最后复现成功了么

**Comment by ruin1732** [comment]
您好，请问您最后复现成功了么

> 您好，我想复现这个实验。我这边有一台可编程交换机，但是我不知道该怎么操作，具体来说就是整个实验的过程指导...请问有详细点的readme文档吗？
